# https://www.paolomainardi.com/posts/linux-remapping-keys-with-xremap/
# Setup systemd service at ~/.config/systemd/$USER/xremap.service
# systemctl --user enable xremap
# systemctl --user start xremap

# https://github.com/xremap/xremap/discussions/640
# Remapped arrow keys behave differently from real arrow keys. And the
# developer said immediately switching between keymaps without first
# releasing the previous one is an unimplemented feature.
#
# virtual_modifiers:
#   - CapsLock
#
# modmap:
#   - name: Global
#     remap:
#       CapsLock: 
#         held: CapsLock
#         alone: Esc
#         alone_timeout_millis: 0
keymap:
#   - name: Remap (virtual_modifier) CapsLock+hjkl to arrow keys
#     remap:
#       CapsLock-h: Left
#       CapsLock-j: Down
#       CapsLock-k: Up
#       CapsLock-l: Right

  - name: Remap Super+MouseWheel to scroll between workspaces
    # https://github.com/pop-os/cosmic-epoch/issues/773#issuecomment-4363509668
    remap:
     LeftMeta-XUpScroll: LeftCtrl-LeftMeta-Up
     LeftMeta-XDownScroll: LeftCtrl-LeftMeta-Down
